# Generated by Django 4.2.11 on 2024-05-30 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Імя')),
                ('surname', models.CharField(max_length=35, verbose_name='Прізвище')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кліента',
                'verbose_name_plural': 'Кліент',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[(None, 'Виберіть тип тварини'), ('cat', 'Кішка'), ('dog', 'Собака'), ('hare', 'Заєц'), ('shinshila', 'Шиншила')], max_length=20)),
            ],
            options={
                'verbose_name': 'Тваринка',
                'verbose_name_plural': 'Тваринки',
                'ordering': ['animal'],
            },
        ),
        migrations.CreateModel(
            name='ClientAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3, verbose_name='Вік тваринки')),
                ('description', models.TextField(verbose_name='Опис тваринки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.client')),
                ('typeanimal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.typeanimal')),
            ],
            options={
                'verbose_name': 'Тваринка клієнта',
                'verbose_name_plural': 'Тваринка клієнта',
                'ordering': ['typeanimal'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20, verbose_name='Час прийому')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.client')),
            ],
            options={
                'verbose_name': 'Запис на прийом',
                'verbose_name_plural': 'Запис на прийом',
            },
        ),
    ]
